### ISSUE TITLE
Links are not followed in VS Code version 1.14.1

### ISSUE THREAD

**Issue by troelsbentsen** [SanderLedegen/vscode-angular-follow-selector#6]
I got an enforced update to version VS Code 1.14.1 on January 26 2020 due to my Companys update policy. Now angular-follow-selector is no longer able to follow links in html template files.

**Comment by troelsbentsen** [comment]
Seems like after updating other extensions and restarting it now works. I will test some more. Sorry for the inconvenience

**Comment by SanderLedegen** [comment]
No problem :) I can highly advise you to use following VS Code extension, though; [Angular Language server](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template). It's way more robust, has more features and is, of course, still being maintained.
